---
- name: 1.6.1.2 Ensure the SELinux state is enforcing 
  selinux:
    policy: targeted
    state: enforcing
  register: result


- name: To File
  block:
    - name: Failed
      lineinfile:
        dest: ./results/{{ customer }}-{{ scan_type }}-{{ inventory_hostname }}.txt
        line: "1.6.1.2 failed"
        insertafter: EOF
      delegate_to: localhost
      check_mode: False
      when: result is not succeeded

    - name: Success
      lineinfile:
        dest: ./results/{{ customer }}-{{ scan_type }}-{{ inventory_hostname }}.txt
        line: "1.6.1.2 success"
        insertafter: EOF
      delegate_to: localhost
      check_mode: False
      when: result is succeeded
