---
- name: 1.6.1.1 Ensure SELinux is not disabled in bootloader configuration 
  block:
    - name: Reconfiguring SELinux in grub
      replace:
        path: /etc/default/grub
        regexp: 'selinux=0'
        replace: ''
      register: result1

    - name: Reconfiguring SELinux in grub
      replace:
        path: /etc/default/grub
        regexp: 'enforcing=0'
        replace: ''
      register: result2

    - name: Update grub configuration
      shell: 'grub2-mkconfig -o /boot/grub2/grub.cfg'
      when: (result1 is changed) or (result2 is changed)
      register: result


- name: To File
  block:
    - name: Failed
      lineinfile:
        dest: ./results/{{ customer }}-{{ scan_type }}-{{ inventory_hostname }}.txt
        line: "1.6.1.1 failed"
        insertafter: EOF
      delegate_to: localhost
      check_mode: False
      when: result is not succeeded

    - name: Success
      lineinfile:
        dest: ./results/{{ customer }}-{{ scan_type }}-{{ inventory_hostname }}.txt
        line: "1.6.1.1 success"
        insertafter: EOF
      delegate_to: localhost
      check_mode: False
      when: result is succeeded
