---
- name: 1.7.1.5 Ensure permissions on /etc/issue are configured
  file:
    path: /boot/grub2/user.cfg
    state: touch
    owner: root
    group: root
    mode: '644'
  when: result is succeeded
  register: result



- name: To File
  block:
    - name: Failed
      lineinfile:
        dest: ./results/{{ customer }}-{{ scan_type }}-{{ inventory_hostname }}.txt
        line: "1.7.1.5 failed"
        insertafter: EOF
      delegate_to: localhost
      check_mode: False
      when: result is not succeeded

    - name: Success
      lineinfile:
        dest: ./results/{{ customer }}-{{ scan_type }}-{{ inventory_hostname }}.txt
        line: "1.7.1.5 success"
        insertafter: EOF
      delegate_to: localhost
      check_mode: False
      when: result is succeeded
