---
# 1.yml
# All checks within section 1 of the CIS benchmark
- name: 1.1.1.1 Ensure mounting of cramfs filesystems is disabled
  modprobe:
    name: cramfs
    state: absent 
  register: result

- name: To File
  block:
    - name: Failed
      lineinfile:
        dest: ./results/{{ customer }}-{{ scan_type }}-{{ inventory_hostname }}.txt
        line: "1.1.1.1 failed"
        insertafter: EOF
      delegate_to: localhost
      check_mode: False
      when: result is not succeeded

    - name: Success
      lineinfile:
        dest: ./results/{{ customer }}-{{ scan_type }}-{{ inventory_hostname }}.txt
        line: "1.1.1.1 success"
        insertafter: EOF
      delegate_to: localhost
      check_mode: False
      when: result is succeeded
