---
- name: 2.2.1.3 Ensure chrony is configured
  block:
    - name: Check time servers
      shell: 'grep ^server /etc/chrony.conf | cat'
      register: result
      check_mode: False

    - name: Configure Chrony
      replace:
        path: /etc/sysconfig/chronyd
        regexp: '\d*OPTIONS.*'
        replace: 'OPTIONS="-u chrony"'
      register: result

      
- name: Success To File
  block:
    - name: Success
      lineinfile:
        dest: ./results/{{ customer }}-{{ scan_type }}-{{ inventory_hostname }}.txt
        line: "2.2.1.3 success"
        insertafter: EOF
      delegate_to: localhost
      check_mode: False
      when: (result is skipped) or (result.enabled == false)
  rescue:
    - debug:
        msg: "Wasn't successful"

- name: Fail To File
  block:
    - name: Failed
      lineinfile:
        dest: ./results/{{ customer }}-{{ scan_type }}-{{ inventory_hostname }}.txt
        line: "2.2.1.3 failed"
        insertafter: EOF
      delegate_to: localhost
      check_mode: False
      when: (result is not skipped) or (result.enabled)
  rescue:
    - debug:
        msg: "Was successful"
