---
- name: 1.4.1 Ensure permissions on bootloader config are configured
  block:
    - name: Permissions on grub.cfg
      file:
        path: /boot/grub2/grub.cfg
        state: touch
        owner: root
        group: root
        mode: '0600'
      register: result

    - name: Permissions on user.cfg
      file:
        path: /boot/grub2/user.cfg
        state: touch
        owner: root
        group: root
        mode: '0600'
      when: result is succeeded
      register: result



- name: To File
  block:
    - name: Failed
      lineinfile:
        dest: ./results/{{ customer }}-{{ scan_type }}-{{ inventory_hostname }}.txt
        line: "1.4.1 failed"
        insertafter: EOF
      delegate_to: localhost
      check_mode: False
      when: result is not succeeded

    - name: Success
      lineinfile:
        dest: ./results/{{ customer }}-{{ scan_type }}-{{ inventory_hostname }}.txt
        line: "1.4.1 success"
        insertafter: EOF
      delegate_to: localhost
      check_mode: False
      when: result is succeeded
