---
- name: 1.5.1 Ensure core dumps are restricted
  block:
    - name: Restricting core dumps
      lineinfile:
        dest: /etc/security/limits.conf
        line: "* hard core 0"
        insertafter: EOF
      register: result

    - name: Restricting core dumps
      replace:
        path: /etc/sysctl.conf
        regexp: '\d*ds.suid_dumpable*'
        replace: 'fs.suid_dumpable = 0'
      when: result is succeeded
      register: result
 
    - name: Restarting process
      shell: 'sysctl -w fs.suid_dumpable=0'
      when: result is succeeded
      register: result



- name: To File
  block:
    - name: Failed
      lineinfile:
        dest: ./results/{{ customer }}-{{ scan_type }}-{{ inventory_hostname }}.txt
        line: "1.5.1 failed"
        insertafter: EOF
      delegate_to: localhost
      check_mode: False
      when: result is not succeeded

    - name: Success
      lineinfile:
        dest: ./results/{{ customer }}-{{ scan_type }}-{{ inventory_hostname }}.txt
        line: "1.5.1 success"
        insertafter: EOF
      delegate_to: localhost
      check_mode: False
      when: result is succeeded
