---
- name: 2.1.7 Ensure xinetd is not enabled
  block:
    - name: Check if xinetd is installed
      yum:
        name: xinetd
        state: absent
      register: result

    - name: Disable xinetd
      systemd:
        name: xinetd
        enabled: no
      when: result is not succeeded


- name: Success To File
  block:
    - name: Success
      lineinfile:
        dest: ./results/{{ customer }}-{{ scan_type }}-{{ inventory_hostname }}.txt
        line: "2.1.7 success"
        insertafter: EOF
      delegate_to: localhost
      check_mode: False
      when: (result is skipped) or (result.enabled == false)
  rescue:
    - debug:
        msg: "Wasn't successful"

- name: Fail To File
  block:
    - name: Failed
      lineinfile:
        dest: ./results/{{ customer }}-{{ scan_type }}-{{ inventory_hostname }}.txt
        line: "2.1.7 failed"
        insertafter: EOF
      delegate_to: localhost
      check_mode: False
      when: (result is not skipped) or (result.enabled)
  rescue:
    - debug:
        msg: "Was successful"
