---
- name: 2.2.11 Ensure IMAP and POP3 Server is not enabled
  block:
    - name: Check if IMAP and POP3 exists
      stat: path=/usr/lib/systemd/system/dovecot.service
      register: exists

    - name: Disable if exists
      service:
        name: dovecot
        state: stopped
        enabled: no
      when: exists.stat.exists
      register: result


- name: Success To File
  block:
    - name: Success
      lineinfile:
        dest: ./results/{{ customer }}-{{ scan_type }}-{{ inventory_hostname }}.txt
        line: "2.2.11 success"
        insertafter: EOF
      delegate_to: localhost
      check_mode: False
      when: (result is skipped) or (result.enabled == false)
  rescue:
    - debug:
        msg: "Wasn't successful"

- name: Fail To File
  block:
    - name: Failed
      lineinfile:
        dest: ./results/{{ customer }}-{{ scan_type }}-{{ inventory_hostname }}.txt
        line: "2.2.11 failed"
        insertafter: EOF
      delegate_to: localhost
      check_mode: False
      when: (result is not skipped) or (result.enabled)
  rescue:
    - debug:
        msg: "Was successful"
