---
- name: 1.2.3 Ensure gpgcheck is globally activated
  block:
    - name: Identifying repository files
      find:
        paths: "/etc/yum.repos.d/"
        patterns: "*.repo"
      register: repos

    - name: Enabling GPGCheck
      replace: 
        path: "{{ item.path }}"
        regexp: 'gpgcheck=0'
        replace: 'gpgcheck=1'
      with_items: "{{ repos.files }}"
      register: result


- name: To File
  block:
    - name: Failed
      lineinfile:
        dest: ./results/{{ customer }}-{{ scan_type }}-{{ inventory_hostname }}.txt
        line: "1.2.3 failed"
        insertafter: EOF
      delegate_to: localhost
      check_mode: False
      when: result is not succeeded

    - name: Success
      lineinfile:
        dest: ./results/{{ customer }}-{{ scan_type }}-{{ inventory_hostname }}.txt
        line: "1.2.3 success"
        insertafter: EOF
      delegate_to: localhost
      check_mode: False
      when: result is succeeded
