---
- name: 1.1.17 Ensure noexec option set on /dev/shm partition
  shell: 'mount | grep /dev/shm | grep noexec | cat'
  register: result
  check_mode: False


- name: To File
  block:
    - name: Failed
      lineinfile:
        dest: ./results/{{ customer }}-{{ scan_type }}-{{ inventory_hostname }}.txt
        line: "1.1.17 failed"
        insertafter: EOF
      delegate_to: localhost
      check_mode: False
      when: result.stdout == ''

    - name: Success
      lineinfile:
        dest: ./results/{{ customer }}-{{ scan_type }}-{{ inventory_hostname }}.txt
        line: "1.1.17 success"
        insertafter: EOF
      delegate_to: localhost
      check_mode: False
      when: result.stdout != ''
