---
- name: 1.1.22 Disable Automounting
  block:
    - name: Check if autofs is installed
      yum:
        name: autofs
        state: absent
      register: result

    - name: Disable autofs
      systemd:
        name: autofs
        enabled: no
      when: result is not succeeded 
  


- name: To File
  block:
    - name: Failed
      lineinfile:
        dest: ./results/{{ customer }}-{{ scan_type }}-{{ inventory_hostname }}.txt
        line: "1.1.22 failed"
        insertafter: EOF
      delegate_to: localhost
      check_mode: False
      when: result is not succeeded

    - name: Success
      lineinfile:
        dest: ./results/{{ customer }}-{{ scan_type }}-{{ inventory_hostname }}.txt
        line: "1.1.22 success"
        insertafter: EOF
      delegate_to: localhost
      check_mode: False
      when: result is succeeded
