---
- name: 1.1.8 Ensure nodev option set on /var/tmp partition
  shell: 'mount | grep /var/tmp | grep nodev | cat'
  register: result
  check_mode: False


- name: To File
  block:
    - name: Failed
      lineinfile:
        dest: ./results/{{ customer }}-{{ scan_type }}-{{ inventory_hostname }}.txt
        line: "1.1.8 failed"
        insertafter: EOF
      delegate_to: localhost
      check_mode: False
      when: result.stdout == ''

    - name: Success
      lineinfile:
        dest: ./results/{{ customer }}-{{ scan_type }}-{{ inventory_hostname }}.txt
        line: "1.1.8 success"
        insertafter: EOF
      delegate_to: localhost
      check_mode: False
      when: result.stdout != ''
