---
- name: 1.1.12 Ensure separate partition exists for /var/log/audit
  shell: 'mount | grep /var/log/audit | cat'
  register: result
  check_mode: False


- name: To File
  block:
    - name: Failed
      lineinfile:
        dest: ./results/{{ customer }}-{{ scan_type }}-{{ inventory_hostname }}.txt
        line: "1.1.12 failed"
        insertafter: EOF
      delegate_to: localhost
      check_mode: False
      when: result.stdout == ''

    - name: Success
      lineinfile:
        dest: ./results/{{ customer }}-{{ scan_type }}-{{ inventory_hostname }}.txt
        line: "1.1.12 success"
        insertafter: EOF
      delegate_to: localhost
      check_mode: False
      when: result.stdout != ''
