---
- name: 2.3.3 Ensure talk client is not installed
  yum:
    name: talk
    state: removed
  register: result


- name: Success To File
  block:
    - name: Success
      lineinfile:
        dest: ./results/{{ customer }}-{{ scan_type }}-{{ inventory_hostname }}.txt
        line: "2.3.3 success"
        insertafter: EOF
      delegate_to: localhost
      check_mode: False
      when: result is not changed
  rescue:
    - debug:
        msg: "Wasn't successful"

- name: Fail To File
  block:
    - name: Failed
      lineinfile:
        dest: ./results/{{ customer }}-{{ scan_type }}-{{ inventory_hostname }}.txt
        line: "2.3.3 failed"
        insertafter: EOF
      delegate_to: localhost
      check_mode: False
      when: result is changed
  rescue:
    - debug:
        msg: "Was successful"
